// Generated by CoffeeScript 1.6.2
/*
  Define functions for parsing rule bodies and expressions

  function parseConstraint(expression) --> List
    expression --> string expression to be parsed
  returns a nested list representing the string expression parsed by defined CFG

  function parseRuleSet(source) --> Hash
    source --> string containing rule definitions
  returns a hash of context parameters of rules defined in source string
*/


(function() {
  (function() {
    "use strict";
    var constraintParser, noolParser;

    constraintParser = require('./constraint/parser');
    noolParser = require('./nools/nool.parser');
    exports.parseConstraint = function(expression) {
      var e;

      try {
        return constraintParser.parse(expression);
      } catch (_error) {
        e = _error;
        throw new Error("Invalid expression '" + expression + "'");
      }
    };
    return exports.parseRuleSet = function(source) {
      return noolParser.parse(source);
    };
  })();

}).call(this);
