nools = require('../../index')
flow = nools.compile('rule.nools')
Machine = flow.getDefined("machine")
m1 = new Machine('Type2', 'DNS Server')
m2 = new Machine('Type2', 'Gateway')
console.log("----------------- Initial Values ---------------------")
console.log("Test for m1 : " + m1.testsList)
console.log("Test for m2 : " + m2.testsList)
console.log("------------------------------------------------------")
flow.assert(m1)
flow.assert(m2)
flow.match()
console.log("\n----------------- Final Values ---------------------")
console.log("Test for m1 : %j", m1.testsList)
console.log("Test for m2 : %j", m2.testsList)
console.log("------------------------------------------------------")
